Repository NaviyaOrganization/Naviya, pull requests merged in 2024-10, with the labels that each got.

#34 [Feature] : #30 - 회원 정보 시스템 기능 구현
  build.gradle
  src/main/java/com/mycom/myapp/naviya/domain/child/entity/.gitkeep
  src/main/java/com/mycom/myapp/naviya/domain/common/entity/Admin.java
  src/main/java/com/mycom/myapp/naviya/domain/user/controller/.gitkeep
  src/main/java/com/mycom/myapp/naviya/domain/user/controller/UserController.java
  src/main/java/com/mycom/myapp/naviya/domain/user/dto/.gitkeep
  src/main/java/com/mycom/myapp/naviya/domain/user/dto/SignupRequestDto.java
  src/main/java/com/mycom/myapp/naviya/domain/user/dto/SignupResultDto.java
  src/main/java/com/mycom/myapp/naviya/domain/user/dto/UserDto.java
  src/main/java/com/mycom/myapp/naviya/domain/user/dto/UserResultDto.java
  src/main/java/com/mycom/myapp/naviya/domain/user/entity/User.java
  src/main/java/com/mycom/myapp/naviya/domain/user/repository/.gitkeep
  src/main/java/com/mycom/myapp/naviya/domain/user/repository/UserRepository.java
  src/main/java/com/mycom/myapp/naviya/domain/user/service/.gitkeep
  src/main/java/com/mycom/myapp/naviya/domain/user/service/UserService.java
  src/main/java/com/mycom/myapp/naviya/domain/user/service/UserServiceImpl.java
  src/main/java/com/mycom/myapp/naviya/global/config/CommonResponse.java
  src/main/java/com/mycom/myapp/naviya/global/config/SecurityConfig.java
  src/main/java/com/mycom/myapp/naviya/global/controller/PageController.java
  src/main/java/com/mycom/myapp/naviya/global/security/.gitkeep
  src/main/java/com/mycom/myapp/naviya/global/security/config/SecurityConfig.java
  src/main/java/com/mycom/myapp/naviya/global/security/dto/CustomUserDetails.java
  src/main/java/com/mycom/myapp/naviya/global/security/service/CustomUserDetailService.java
  src/main/resources/static/navtoggle.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/main.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/userpage.html
Labels: 💥feature

#38 [Feat] 자녀 시스템 기능 구현 및 세션 정보 저장
  src/main/java/com/mycom/myapp/naviya/domain/child/controller/.gitkeep
  src/main/java/com/mycom/myapp/naviya/domain/child/controller/ChildController.java
  src/main/java/com/mycom/myapp/naviya/domain/child/dto/.gitkeep
  src/main/java/com/mycom/myapp/naviya/domain/child/dto/ChildAddDto.java
  src/main/java/com/mycom/myapp/naviya/domain/child/dto/ChildDto.java
  src/main/java/com/mycom/myapp/naviya/domain/child/dto/ChildFavCategoryDto.java
  src/main/java/com/mycom/myapp/naviya/domain/child/dto/ChildResultDto.java
  src/main/java/com/mycom/myapp/naviya/domain/child/entity/Child.java
  src/main/java/com/mycom/myapp/naviya/domain/child/entity/ChildFavorCategory.java
  src/main/java/com/mycom/myapp/naviya/domain/child/repository/.gitkeep
  src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildFavorCategoryRepository.java
  src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildRepository.java
  src/main/java/com/mycom/myapp/naviya/domain/child/service/.gitkeep
  src/main/java/com/mycom/myapp/naviya/domain/child/service/ChildService.java
  src/main/java/com/mycom/myapp/naviya/domain/child/service/ChildServiceImpl.java
  src/main/java/com/mycom/myapp/naviya/domain/common/entity/.gitkeep
  src/main/java/com/mycom/myapp/naviya/domain/common/repository/.gitkeep
  src/main/java/com/mycom/myapp/naviya/domain/common/repository/CodeRepository.java
  src/main/java/com/mycom/myapp/naviya/domain/user/controller/UserController.java
  src/main/java/com/mycom/myapp/naviya/domain/user/entity/User.java
  src/main/java/com/mycom/myapp/naviya/domain/user/service/UserService.java
  src/main/java/com/mycom/myapp/naviya/domain/user/service/UserServiceImpl.java
  src/main/java/com/mycom/myapp/naviya/global/controller/PageController.java
  src/main/java/com/mycom/myapp/naviya/global/security/config/CustomLoginSuccessHandler.java
  src/main/java/com/mycom/myapp/naviya/global/security/config/SecurityConfig.java
  src/main/resources/static/assets/img/image1.png
  src/main/resources/static/assets/img/image2.png
  src/main/resources/static/navtoggle.html
  src/main/resources/templates/childAdd.html
  src/main/resources/templates/childImageUpdate.html
  src/main/resources/templates/childPage.html
  src/main/resources/templates/childSelectPage.html
  src/main/resources/templates/childUpdate.html
  src/main/resources/templates/index.html
  src/main/resources/templates/main.html
  src/main/resources/templates/userPage.html
Labels: 💥feature

#42 [Feat] 세션 스토리지 저장
  src/main/java/com/mycom/myapp/naviya/domain/child/controller/ChildController.java
  src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildRepository.java
  src/main/java/com/mycom/myapp/naviya/global/controller/PageController.java
  src/main/resources/templates/childSelectPage.html
  src/main/resources/templates/index.html
Labels: 😉enhancement

#45 [Feature] : #43 자녀 성향 진단 데이터 물리적 삭제 기능 추가 및 수정
  build.gradle
  src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildBookDisLikeRepository.java
  src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildBookLikeRepository.java
  src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildFavorCategoryRepository.java
  src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildMbtiHistoryRepository.java
  src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildMbtiRepository.java
  src/main/java/com/mycom/myapp/naviya/domain/child/service/ChildMbtiServiceImpl.java
  src/main/java/com/mycom/myapp/naviya/global/config/QuartzConfig.java
  src/main/java/com/mycom/myapp/naviya/global/config/SchedulerConfig.java
  src/main/java/com/mycom/myapp/naviya/global/mbti/service/MbtiDiagnosisDataQuartzService.java
  src/main/java/com/mycom/myapp/naviya/global/mbti/service/MbtiDiagnosisDataSchedulerService.java
  src/main/java/com/mycom/myapp/naviya/global/scheduler/ChildDeletionJob.java
Labels: 😉enhancement, 💥feature

#46 [Feat] 메인페이지 및 mbti 별 반대 성향 추천 로직 구현
  src/main/java/com/mycom/myapp/naviya/domain/book/controller/BookController.java
  src/main/java/com/mycom/myapp/naviya/domain/book/service/MbtiRecommendService.java
  src/main/java/com/mycom/myapp/naviya/domain/book/service/MbtiRecommendServiceImpl.java
  src/main/resources/static/mains.html
  src/main/resources/templates/index.html
  src/main/resources/templates/search.html
Labels: 😉enhancement, 💥feature

#47 #47 Feat category recommend,like,dislike feadback
  src/main/java/com/mycom/myapp/naviya/domain/book/controller/BookController.java
  src/main/java/com/mycom/myapp/naviya/domain/book/repository/BookFavorTotalRepository.java
  src/main/java/com/mycom/myapp/naviya/domain/book/repository/BookRepository.java
  src/main/java/com/mycom/myapp/naviya/domain/book/service/BookSerive.java
  src/main/java/com/mycom/myapp/naviya/domain/book/service/BookServiceImpl.java
  src/main/java/com/mycom/myapp/naviya/domain/child/controller/ChildController.java
  src/main/java/com/mycom/myapp/naviya/domain/child/dto/ChildCategoryDto.java
  src/main/java/com/mycom/myapp/naviya/domain/child/dto/ChildDto.java
  src/main/java/com/mycom/myapp/naviya/domain/child/dto/ChildFavCategoryDto.java
  src/main/java/com/mycom/myapp/naviya/domain/child/entity/ChildMbti.java
  src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildBookDisLikeRepository.java
  src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildBookLikeRepository.java
  src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildFavorCategoryRepository.java
  src/main/java/com/mycom/myapp/naviya/domain/child/service/ChildServiceImpl.java
  src/main/java/com/mycom/myapp/naviya/global/scheduler/ChildDeletionJob.java
  src/main/java/com/mycom/myapp/naviya/global/security/config/SecurityConfig.java
  src/main/resources/static/ChildFavorBookList.html
Labels: 😉enhancement, 💥feature

#48 #Feat adjust query
  src/main/java/com/mycom/myapp/naviya/domain/book/controller/BookController.java
  src/main/java/com/mycom/myapp/naviya/domain/book/repository/BookRepository.java
  src/main/java/com/mycom/myapp/naviya/domain/book/service/BookSerive.java
  src/main/java/com/mycom/myapp/naviya/domain/book/service/BookServiceImpl.java
  src/main/java/com/mycom/myapp/naviya/domain/book/service/MbtiRecommendServiceImpl.java
  src/main/java/com/mycom/myapp/naviya/domain/child/entity/Child.java
  src/main/java/com/mycom/myapp/naviya/domain/child/entity/ChildMbti.java
  src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildMbtiRepository.java
  src/main/java/com/mycom/myapp/naviya/global/controller/PageController.java
  src/main/java/com/mycom/myapp/naviya/global/security/config/SecurityConfig.java
  src/main/resources/static/ChildFavorBookList.html
  src/main/resources/static/navtoggle.html
  src/main/resources/templates/BookCategoryHtml.html
  src/main/resources/templates/ChildRecentReadBook.html
  src/main/resources/templates/childAdd.html
  src/main/resources/templates/childPage.html
  src/main/resources/templates/childSelectPage.html
  src/main/resources/templates/childUpdate.html
  src/main/resources/templates/index.html
  src/main/resources/templates/userPage.html
Labels: 😒chore, 💥feature

#51 [FEATURE] 자녀 시스템 조회 수정 삭제 기능 구현
  src/main/java/com/mycom/myapp/naviya/domain/child/controller/ChildController.java
  src/main/java/com/mycom/myapp/naviya/domain/child/dto/ChildSelectDto.java
  src/main/java/com/mycom/myapp/naviya/domain/child/dto/ChildUpdateRequestDto.java
  src/main/java/com/mycom/myapp/naviya/domain/child/entity/Child.java
  src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildFavorCategoryRepository.java
  src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildRepository.java
  src/main/java/com/mycom/myapp/naviya/domain/child/service/ChildService.java
  src/main/java/com/mycom/myapp/naviya/domain/child/service/ChildServiceImpl.java
  src/main/java/com/mycom/myapp/naviya/global/controller/PageController.java
  src/main/java/com/mycom/myapp/naviya/global/mbti/entity/Mbti.java
  src/main/java/com/mycom/myapp/naviya/global/security/config/SecurityConfig.java
  src/main/resources/static/assets/css/sidebar.css
  src/main/resources/static/assets/img/profile1.png
  src/main/resources/static/assets/img/profile2.png
  src/main/resources/static/assets/img/profile3.png
  src/main/resources/static/assets/img/profile4.png
  src/main/resources/static/assets/img/profile5.png
  src/main/resources/static/assets/img/profile6.png
  src/main/resources/static/assets/img/profile7.png
  src/main/resources/static/assets/img/profile8.png
  src/main/resources/static/assets/img/profile9.png
  src/main/resources/static/assets/js/sidebar.js
  src/main/resources/static/navtoggle.html
  src/main/resources/templates/childAdd.html
  src/main/resources/templates/childImageUpdate.html
  src/main/resources/templates/childPage.html
  src/main/resources/templates/childSelectPage.html
  src/main/resources/templates/childUpdate.html
  src/main/resources/templates/login.html
  src/main/resources/templates/userPage.html
Labels: 💥feature

#55 [FEATURE] #33 자녀 시스템 조회 수정 삭제 기능 구현
  build.gradle
  src/main/java/com/mycom/myapp/naviya/NaviyaApplication.java
  src/main/java/com/mycom/myapp/naviya/domain/lottery/dto/LotteryEntryRequest.java
  src/main/java/com/mycom/myapp/naviya/domain/lottery/entity/LotteryEntry.java
  src/main/java/com/mycom/myapp/naviya/domain/lottery/service/LotteryServiceImpl.java
  src/main/resources/templates/lotteryForm.html
Labels: 💥feature, 👻test

#61 [FEATURE] #56 대규모 응모 시스템 테스트 및 최적화
  build.gradle
  src/load-tests/serialtest.js
  src/load-tests/traffictest.js
  src/main/java/com/mycom/myapp/naviya/domain/lottery/controller/LotteryController.java
  src/main/java/com/mycom/myapp/naviya/domain/lottery/service/HashLotteryService.java
  src/main/java/com/mycom/myapp/naviya/domain/lottery/service/ListLotteryService.java
  src/main/java/com/mycom/myapp/naviya/domain/lottery/service/LuaAndQueueLotteryService.java
  src/main/java/com/mycom/myapp/naviya/domain/lottery/service/LuaLotteryService.java
Labels: 😒chore, 😉enhancement, 💥feature, 😎refactor, 👻test

#63 [FEATURE] #62 응모 이벤트 페이지 디자인, 체험형 프로그램 기능 추가
  src/load-tests/serialtest.js
  src/load-tests/traffictest.js
  src/main/java/com/mycom/myapp/naviya/domain/lottery/controller/LotteryController.java
  src/main/java/com/mycom/myapp/naviya/domain/lottery/dto/LotteryEntryRequest.java
  src/main/java/com/mycom/myapp/naviya/domain/lottery/entity/LotteryEntry.java
  src/main/java/com/mycom/myapp/naviya/domain/lottery/service/HashLotteryService.java
  src/main/java/com/mycom/myapp/naviya/domain/lottery/service/ListLotteryService.java
  src/main/java/com/mycom/myapp/naviya/domain/lottery/service/LuaAndQueueLotteryService.java
  src/main/java/com/mycom/myapp/naviya/global/security/config/SecurityConfig.java
  src/main/resources/templates/lotteryForm.html
  src/main/resources/templates/lotteryResult.html
Labels: 😉enhancement, 💥feature

#68 Feat temp adjuset
  src/main/java/com/mycom/myapp/naviya/domain/book/repository/BookRepository.java
  src/main/java/com/mycom/myapp/naviya/domain/book/service/BookServiceImpl.java
  src/main/java/com/mycom/myapp/naviya/domain/child/entity/ChildMbti.java
  src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildMbtiRepository.java
  src/main/java/com/mycom/myapp/naviya/global/controller/PageController.java
  src/main/java/com/mycom/myapp/naviya/global/redies/RedisStreamInitializer.java
  src/main/resources/templates/BookCategoryHtml.html
  src/main/resources/templates/ChildFavorBookList.html
  src/main/resources/templates/ChildRecentReadBook.html
  src/main/resources/templates/index.html
Labels: 😶‍🌫️bug, 😒chore

#69 [Feature] 자녀 프로필 삭제 수정
  src/main/java/com/mycom/myapp/naviya/domain/child/controller/ChildController.java
  src/main/java/com/mycom/myapp/naviya/domain/child/entity/Child.java
  src/main/java/com/mycom/myapp/naviya/global/controller/PageController.java
  src/main/resources/templates/childAdd.html
  src/main/resources/templates/childAddAskMbti.html
  src/main/resources/templates/childPage.html
  src/main/resources/templates/childUpdate.html
Labels: 💥feature

#71 카테고리 존재 확인 api 추가
  src/main/java/com/mycom/myapp/naviya/domain/book/controller/BookController.java
  src/main/java/com/mycom/myapp/naviya/domain/child/controller/ChildMbtiController.java
  src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildFavorCategoryRepository.java
  src/main/java/com/mycom/myapp/naviya/domain/child/service/ChildService.java
  src/main/java/com/mycom/myapp/naviya/domain/child/service/ChildServiceImpl.java
Labels: 😒chore, 💥feature

#73 Feat add category chek
  src/main/java/com/mycom/myapp/naviya/domain/book/service/BookServiceImpl.java
  src/main/java/com/mycom/myapp/naviya/domain/child/controller/ChildMbtiController.java
  src/main/java/com/mycom/myapp/naviya/domain/child/repository/ChildFavorCategoryRepository.java
  src/main/java/com/mycom/myapp/naviya/domain/child/service/ChildService.java
  src/main/java/com/mycom/myapp/naviya/domain/child/service/ChildServiceImpl.java
Labels: 💥feature

#76 [Feature] sidebar, font 수정
  src/main/resources/static/assets/css/newSidebar.css
  src/main/resources/static/newNavtoggle.html
  src/main/resources/templates/BookReadPage.html
  src/main/resources/templates/ChildFavorBookList.html
  src/main/resources/templates/ChildRecentReadBook.html
  src/main/resources/templates/childAdd.html
  src/main/resources/templates/childAddAskMbti.html
  src/main/resources/templates/childMBTIResult.html
  src/main/resources/templates/childPage.html
  src/main/resources/templates/childSelectPage.html
  src/main/resources/templates/childUpdate.html
  src/main/resources/templates/diagnosisForm.html
  src/main/resources/templates/login.html
  src/main/resources/templates/lotteryForm.html
  src/main/resources/templates/mbtiHistory.html
  src/main/resources/templates/search.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/userPage.html
Labels: 😉enhancement, 💥feature

#77 [FEATURE] 메인, 검색 페이지 보완
  build.gradle
  src/main/java/com/mycom/myapp/naviya/domain/book/service/BookServiceImpl.java
  src/main/java/com/mycom/myapp/naviya/domain/child/entity/Child.java
  src/main/java/com/mycom/myapp/naviya/global/mbti/entity/Mbti.java
  src/main/resources/static/assets/js/newSidebar.js
  src/main/resources/templates/index.html
  src/main/resources/templates/search.html
Labels: 💥feature

#79 [FEATURE] 메인 페이지 카테고리 별 책 추천 수정
  src/main/resources/templates/index.html
Labels: 💥feature
